#!/bin/sh

#set -x

TOOLSET=`basename "$0"`
TOOLSET_DIR=$( dirname "${BASH_SOURCE[0]}")

#MINGW_DIR=/usr/local/mingw-w64

if [ -z "$MINGW_DIR" ]; then
    MINGW_DIR=${TOOLSET_DIR}/../../libs/mingw-w64
    mkdir -p $MINGW_DIR
    MINGW_DIR=`readlink -f ${MINGW_DIR}`
fi
export MINGW_DIR


export PATH="$TOOLSET_DIR/..:$PATH"
export NPROC=`nproc --all`

[ -z "$LOG_FILE" ] && LOG_FILE=$PWD/log.txt && export LOG_FILE
