#!/bin/sh

#set -x

TOOLSET=`basename "$0"`
TOOLSET_DIR=$( dirname "${BASH_SOURCE[0]}")

export MINGW_DIR=/usr/local/mingw-w64


export PATH="$TOOLSET_DIR/..:$PATH"
export NPROC=`nproc --all`

[ -z "$LOG_FILE" ] && LOG_FILE=$PWD/log.txt && export LOG_FILE
