#!/bin/sh
#set -x
. $( dirname "${BASH_SOURCE[0]}")/common

PLATFORM=mingw
COMPILER=msvc

ARCH=x86_64
ARCH_DIR=${MINGW_DIR}/toolchain-${ARCH}
TARGET=${ARCH}-w64-mingw32

export PKG_CONFIG_PATH=${ARCH_DIR}/${TARGET}/lib/pkgconfig:${PKG_CONFIG_PATH}
export PATH="/mnt/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64:$PATH"




