#!/bin/sh
#set -x
. $( dirname "${BASH_SOURCE[0]}")/common

PLATFORM=mingw32
COMPILER=gcc

ARCH=x86_64
ARCH_DIR=${PREFIX}/toolchain-${ARCH}
TARGET=${ARCH}-w64-mingw32

export PKG_CONFIG_PATH=${ARCH_DIR}/${TARGET}/lib/pkgconfig:${PKG_CONFIG_PATH}
export PATH="${ARCH_DIR}/bin:$PATH"
